/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module3;

/**
 *
 * @author Cindy
 */
public class MultiThreading extends javax.swing.JFrame {
    
    private Thread th;
    private Thread th2;
    private Thread th3;
    
    private MultiThread runs;       
    
    public MultiThreading() {
        initComponents();
        runs = new MultiThread();
        th = new Thread(runs);
        th.setName("CAT");
        th2 = new Thread(th);
        th2.setName("DOG");
        th3 = new Thread(th);
        th3.setName("MONKEY");
        setThreadNames();
    }
    
    public void setThreadNames(){
        jLabelFirst.setText(th.getName());
        jLabelSecond.setText(th2.getName());
        jLabelThird.setText(th3.getName());
    }
    
    public void setStatis(){
        statuThird.setText("" + th3.getState());
        statuSecond.setText("" + th2.getState());
        statuFirst.setText("" + th.getState());
        
        if(th.getState() == Thread.State.RUNNABLE){
            jLabel2.setText("Im " + th.getName() + " and Im running");
        }else if(th2.getState() == Thread.State.RUNNABLE){            
            jLabel2.setText("Im " + th2.getName() + " and Im running");
        }else if(th3.getState() == Thread.State.RUNNABLE){
            jLabel2.setText("Im " + th3.getName() + " and Im running");
        }else{
            jLabel2.setText("Im not running");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFirst = new javax.swing.JLabel();
        jLabelThird = new javax.swing.JLabel();
        jLabelSecond = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        statuFirst = new javax.swing.JLabel();
        statuSecond = new javax.swing.JLabel();
        statuThird = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("STOP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("THREADS");

        jLabelFirst.setBackground(new java.awt.Color(204, 204, 204));
        jLabelFirst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFirst.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFirst.setText("THREADS");
        jLabelFirst.setOpaque(true);

        jLabelThird.setBackground(new java.awt.Color(204, 204, 204));
        jLabelThird.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelThird.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelThird.setText("THREADS");
        jLabelThird.setOpaque(true);

        jLabelSecond.setBackground(new java.awt.Color(204, 204, 204));
        jLabelSecond.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSecond.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSecond.setText("THREADS");
        jLabelSecond.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("STATUS");

        statuFirst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        statuFirst.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statuFirst.setText("THREADS");

        statuSecond.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        statuSecond.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statuSecond.setText("THREADS");

        statuThird.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        statuThird.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statuThird.setText("THREADS");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabelSecond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelThird, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(statuSecond, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(statuFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statuThird, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabelFirst)
                        .addGap(41, 41, 41)
                        .addComponent(jLabelSecond)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelThird))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(statuFirst)
                        .addGap(41, 41, 41)
                        .addComponent(statuSecond)
                        .addGap(36, 36, 36)
                        .addComponent(statuThird)))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            th.stop();
            th2.stop();
            th3.stop();
            setStatis();

        } catch (Exception ex) {
            System.out.println("Cannot stop when it's not starting");
        }
        setStatis();
        
    }//GEN-LAST:event_jButton2ActionPerformed
        private int time = 1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        if(time == 2){
            th = new Thread(runs);
            th.setName("CAT");
            th2 = new Thread(th);
            th2.setName("DOG");
            th3 = new Thread(th);
            th3.setName("MONKEY");
            setThreadNames();
        }
        if(!th.isAlive() || !th2.isAlive() || !th3.isAlive()){
            th.start();
            th2.start();
            th3.start();
            time = 2;
        }else{
            System.out.println("Thread is alive");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
        private String name = null;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiThreading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiThreading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiThreading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiThreading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiThreading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFirst;
    private javax.swing.JLabel jLabelSecond;
    private javax.swing.JLabel jLabelThird;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel statuFirst;
    private javax.swing.JLabel statuSecond;
    private javax.swing.JLabel statuThird;
    // End of variables declaration//GEN-END:variables
    class MultiThread implements Runnable{

        @Override
        public void run() {
            try {
                while (true) {  
                    Thread.sleep(300);
                    setStatis();

                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
             
        }
        
    }

}
